version: "3"
services:
  web:
    container_name: web
    image: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx/remote/default/default.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/local/site.template:/etc/nginx/conf.d/site.template:rw
    environment:
      - LOCAL_IP=$LOCAL_IP
    command: /bin/bash -c "envsubst '$${LOCAL_IP}'< /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  postgres:
    container_name: postgresdb
    image: "postgres:11.5-alpine"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_HOST: $MYSQL_ROOT_HOST
    ports:
      - 3301:3306
    expose:
      - 3306
volumes:
  postgres:
    driver: local
  mysql:
    driver: local
